os: windows
language: cpp
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
install:
  - nuget.exe install Microsoft.TestPlatform.ObjectModel -Version 16.4.0-preview-20191007-01 -Source https://dotnet.myget.org/F/vstest/api/v3/index.json
script:
  - export PATH=$MSBUILD_PATH:$PATH
  - MSBuild.exe -p:Configuration=Release -p:Platform=x64 umlaut.sln
  - 